/* This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number. */
import inquirer from "inquirer";
let score = 0;
let round = 0;
console.log("Welcome to Guess the Number Game 🎉");
console.log("Guess the number between 1 and 15");
async function RandomGussings() {
    let numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
    let randomNumGenerator = numbers[Math.floor(Math.random() * numbers.length)];
    console.log(randomNumGenerator);
    let prompt = await inquirer.prompt([
        {
            type: "number",
            name: "guess",
            message: "Guess the number between 1 and 15"
        }
    ]);
    if (prompt.guess === randomNumGenerator) {
        console.log("Thats the right guess 🥳");
        score++;
        round++;
    }
    else {
        console.log("Wrong Guess 😓");
        score--;
        round++;
    }
}
async function startGame() {
    await RandomGussings();
    let againPrompt;
    do {
        againPrompt = await inquirer.prompt([
            {
                type: "confirm",
                name: "confirm",
                message: "Wana have an other round?😉"
            }
        ]);
        if (againPrompt.confirm === true) {
            console.log("Good Luck 😊");
            await RandomGussings();
        }
        else {
            console.log(`You score is ${score} and you have played ${round} ${round === 1 ? "round" : "rounds"}!!`);
            console.log("Good Bye 🙂");
        }
    } while (againPrompt.confirm);
}
startGame();
